# Site settings
title: how to make [almost] anything
email: matt@arbesfeld.com
author: matthew arbesfeld
description: "Matthew Arbesfeld's website for MAS.863 -- How to Make Almost Anything"
baseurl: ""
url: "http://www.arbesfeld.com"
google_analytics:
animated: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
